-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.admission
(
    admins_id integer NOT NULL,
    initial_admission text,
    PRIMARY KEY (admins_id)
);

CREATE TABLE public.complication
(
    complication_id integer NOT NULL,
    complication_risk text,
    PRIMARY KEY (complication_id)
);

CREATE TABLE public.job
(
    job_id integer NOT NULL,
    job_title text,
    PRIMARY KEY (job_id)
);

CREATE TABLE public.location
(
    location_id integer NOT NULL,
    zip integer,
    city text,
    state text,
    county text,
    PRIMARY KEY (location_id)
);

CREATE TABLE public.patient
(
    patient_id text NOT NULL,
    lat numeric,
    lng numeric,
    population integer,
    children integer,
    age integer,
    income numeric,
    marital text,
    readmis text,
    gender text,
    initial_days numeric,
    totalcharge numeric,
    additional_charges numeric,
    vitd_levels numeric,
    doc_visits integer,
    full_meals integer,
    vitd_supp integer,
    soft_drink text,
    hignblood text,
    stroke text,
    job_id integer,
    compl_id integer,
    admis_id integer,
    location_id integer,
    PRIMARY KEY (patient_id)
);

CREATE TABLE public.servicesaddon
(
    patient_id text NOT NULL,
    services text,
    overweight text,
    arthritis text,
    diabetes text,
    hyperlipidemia text,
    backpain text,
    anxiety text,
    allergic_rhinitis text,
    reflux_esophagitis text,
    asthma text,
    PRIMARY KEY (patient_id)
);

CREATE TABLE public.survey_responses_addon
(
    patient_id text NOT NULL,
    item1 integer,
    item2 integer,
    item3 integer,
    item4 integer,
    item5 integer,
    item6 integer,
    item7 integer,
    item8 integer,
    PRIMARY KEY (patient_id)
);

ALTER TABLE public.patient
    ADD FOREIGN KEY (admis_id)
    REFERENCES public.admission (admins_id)
    NOT VALID;


ALTER TABLE public.patient
    ADD FOREIGN KEY (compl_id)
    REFERENCES public.complication (complication_id)
    NOT VALID;


ALTER TABLE public.patient
    ADD FOREIGN KEY (job_id)
    REFERENCES public.job (job_id)
    NOT VALID;


ALTER TABLE public.patient
    ADD FOREIGN KEY (location_id)
    REFERENCES public.location (location_id)
    NOT VALID;

END;